#
# /etc/pacman.conf
#
# Synapse Linux Package Manager Configuration
#
# See the pacman.conf(5) man page for option and repository directives.
#

#
# GENERAL OPTIONS
#
[options]

# The following paths are commented out with their default values.
# Uncomment and modify them only if custom locations are required.
#RootDir     = /
#DBPath      = /var/lib/pacman/
#CacheDir    = /var/cache/pacman/pkg/
#LogFile     = /var/log/pacman.log
#GPGDir      = /etc/pacman.d/gnupg/
#HookDir     = /etc/pacman.d/hooks/

HoldPkg     = pacman glibc
Architecture = auto

# Pacman will not upgrade packages listed here.
#IgnorePkg   =
#IgnoreGroup =

# Files listed here will not be overwritten during package upgrades.
NoUpgrade   =
#NoExtract   =

# Miscellaneous options
Color
CheckSpace
ParallelDownloads = 5
DownloadUser = alpm

# Package signature verification.
SigLevel = Required DatabaseOptional
LocalFileSigLevel = Optional
#RemoteFileSigLevel = Required

#
# REPOSITORIES
#
# Repositories are searched in the order listed below.
# Repository URLs are provided by the included mirror list.
# The variables $repo and $arch are substituted automatically by pacman.
#

[synapse-core]
SigLevel = Optional TrustAll
Server = https://synapse-eco.github.io/synapse-repo

#[core-testing]
#Include = /etc/pacman.d/mirrorlist

[core]
Include = /etc/pacman.d/mirrorlist

#[extra-testing]
#Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

# If you want to run 32 bit applications on your x86_64 system,
# enable the multilib repositories as required here.

#[multilib-testing]
#Include = /etc/pacman.d/mirrorlist

#[multilib]
Include = /etc/pacman.d/mirrorlist

#
# Additional repositories may be added below.
#

#[custom]
#SigLevel = Optional TrustAll
#Server = file:///path/to/repository
#
